---
- name: has httpd installed
  command: rpm -q httpd
  register: cmd_result
  ignore_errors: true

- name: set httpd_installed
  set_fact: httpd_installed = true
  when: cmd_result | success

- name: replace security configuration
  lineinfile:
    path: /tmp/httpd.conf.217
    backup: yes
    regexp: '{{ item.regexp }}'
    state: present
    line: '{{ item.line }}'
  with_items:
    - { regexp: '^ServerTokens', line: 'ServerTokens Prod' }
    - { regexp: '^ServerSignature', line: 'ServerSignature Off' }
    - { regexp: '^TraceEnable', line: 'TraceEnable Off' }
  when: httpd_installed is defined and httpd_installed == true

- name: no indexes options
  replace:
    path: /tmp/httpd.conf.217
    backup: yes
    regexp: '^(\s*Options.*)(Indexes\s*)(.*)'
    replace: '\1\3'
  when: httpd_installed is defined and httpd_installed == true
