- name: config rc file
  hosts: chenxueying
  remote_user: project0xxx
  become: true
  become_user: project0xxx
  gather_facts: false
  strategy: free
  tasks:
    - copy:
        src: /home/git/projectxxx/backend/project0xxx/ansible/keystonerc_admin.j2
        dest: /home/project0xxx/keystonerc_admin
        owner: project0xxx
        group: project0xxx
        mode: 0666
        force: yes
  tags: rc_file
