---
- name: dfasdfasdfasdfasdfas
#  hosts: liyuying
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: recusively copy directory to remote
      copy:
        src: /home/tmp/projectxxx/xxx
        dest: /tmp/
        directory_mode: "0755"
        # recurse: yes   # no recurse in module 'copy'
        mode: 0755
