- name: config rc file
  hosts: chenxueying
  vars:
    PUBLIC_IP: "172.255.201.170"
  remote_user: project0xxx
  become: true
  become_user: project0xxx
  gather_facts: false
  strategy: free
  tasks:
    - name: do what ...
      vars:
        PUBLIC_IP: "10.20.30.40"
      template:
        src: /home/git/projectxxx/backend/project0xxx/ansible/keystonerc_admin.j2
        dest: /home/project0xxx/keystonerc_admin
        owner: project0xxx
        group: project0xxx
        mode: 0666
        force: yes
  tags: rc_file
