- name: config rc file
  hosts: chenxueying
  vars:
    PUBLIC_IP: "172.255.201.170"
  remote_user: tecs
  become: true
  become_user: tecs
  gather_facts: false
  strategy: free
  tasks:
    - name: do what ...
      vars:
        PUBLIC_IP: "10.20.30.40"
      template:
        src: /home/git/daisy/backend/tecs/ansible/keystonerc_admin.j2
        dest: /home/tecs/keystonerc_admin
        owner: tecs
        group: tecs
        mode: 0666
        force: yes
  tags: rc_file
