---
- name: to json or to yaml
  hosts: debughost
  gather_facts: false
  vars:
    users:
      - bob
      - joe
  tasks:
     - name: debug show vars in yaml format
       debug: msg="{{ users | to_yaml }}"

     - name: debug show vars in json format
       debug: msg="{{ users | to_json }}"

