---
- name: Update metadata(store in json or yaml) to INI file
  hosts: localhost
  gather_facts: false
  connection: local
  vars_files: 
    - "meta0.yaml"
  tasks:
#     - name: debug
#       debug:
#         msg: "{{ DEFAULT }}"
    - name: aaaaaaaaaaaaaaaaaaa
      ini_file:
        path: /tmp/nova.conf
        section: "DEFAULT" 
        option: "{{ item.key }}"
        value: "{{ item.value }}"
      with_dict: "{{ DEFAULT }}"
