set term=screen-256color
set t_Co=256
set ts=4
set sw=4
set expandtab
syntax enable
syntax on
set bg=dark
set nu
set hlsearch
"colorscheme random
"colorscheme Chasing_Logic
colorscheme morning
"colorscheme fx
""colorscheme molokai

set fileformat=unix
set fileencoding=utf-8
set fileencodings=ucs-bom,utf-8,cp936,gb18030,big5,euc-jp,euc-kr,latin1
