---
- name: Ansible mysql_db module exercise
  hosts: localhost
  gather_facts: false
  connection: local
  sudo: true
#  sudo_user: root
  tasks:
    - name: Create a new database with name 'bobdata'
      mysql_db:
        name: bobdata
        state: present
    
    # Copy database dump file to remote host and restore it to database 'my_db'
    # - name: Copy database dump file
    #   copy:
    #     src: dump.sql.bz2
    #     dest: /tmp
    # - name: Restore database
    #   mysql_db:
    #     name: my_db
    #     state: import
    #     target: /tmp/dump.sql.bz2
    
    - name: Dump all databases to hostname.sql
      mysql_db:
        state: dump
        name: all
        target: /tmp/{{ inventory_hostname }}.sql
    
    # - name: Import file.sql similar to mysql -u <username> -p <password> < hostname.sql
    #   mysql_db:
    #     state: import
    #     name: all
    #     target: /tmp/{{ inventory_hostname }}.sql
